# Generated by Django 4.2.3 on 2023-07-21 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome Local')),
                ('endereco', models.CharField(max_length=300)),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('fone', models.CharField(max_length=11, verbose_name='Telefone Contato')),
                ('web', models.URLField(verbose_name='HomePage')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Contato')),
            ],
        ),
        migrations.CreateModel(
            name='MyEventoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Promoter')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('data_evento', models.DateTimeField(verbose_name='Data Evento')),
                ('data_final', models.DateTimeField(verbose_name='Data Final')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.local')),
                ('participantes', models.ManyToManyField(blank=True, to='eventos.myeventouser')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
            ],
        ),
    ]
