# Generated by Django 4.2.3 on 2023-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Contato'),
        ),
        migrations.AlterField(
            model_name='local',
            name='fone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone Contato'),
        ),
        migrations.AlterField(
            model_name='local',
            name='web',
            field=models.URLField(blank=True, verbose_name='HomePage'),
        ),
    ]
