# Generated by Django 4.2.3 on 2023-07-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_local_email_alter_local_fone_alter_local_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myeventouser',
            old_name='sobrenome',
            new_name='contato',
        ),
        migrations.AddField(
            model_name='myeventouser',
            name='fuso',
            field=models.TimeField(default='00:00:00', verbose_name='Fuso Horario'),
        ),
    ]
