# Generated by Django 4.2.3 on 2023-07-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_sobrenome_myeventouser_contato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myeventouser',
            old_name='contato',
            new_name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='myeventouser',
            name='fuso',
        ),
    ]
