# Generated by Django 4.2.3 on 2023-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_myeventouser_sobrenome_myeventouser_fuso'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
